# Generated by Django 3.2.4 on 2021-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pretty/')),
                ('title', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pretty/')),
                ('title', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
    ]
