# Generated by Django 3.2.4 on 2021-07-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pretty/')),
                ('title', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prettymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='pretty/'),
        ),
    ]
