# Generated by Django 3.2.4 on 2021-07-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('test1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test12', to='commentapp.commentmodel')),
            ],
        ),
    ]
