# Generated by Django 3.2.4 on 2021-07-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articleapp', '0001_initial'),
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer', to='articleapp.articlecreatemodel')),
                ('writer_nickname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_nickname', to='accountapp.profile')),
            ],
        ),
    ]
