# Generated by Django 3.2.4 on 2021-08-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldcupmodel',
            name='like_1',
            field=models.FloatField(default=1.1),
        ),
        migrations.AlterField(
            model_name='worldcupmodel',
            name='like_2',
            field=models.FloatField(default=1.2),
        ),
        migrations.AlterField(
            model_name='worldcupmodel',
            name='like_3',
            field=models.FloatField(default=1.3),
        ),
        migrations.AlterField(
            model_name='worldcupmodel',
            name='like_4',
            field=models.FloatField(default=1.4),
        ),
        migrations.AlterField(
            model_name='worldcupmodel',
            name='like_5',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='worldcupmodel',
            name='like_6',
            field=models.FloatField(default=1.6),
        ),
        migrations.AlterField(
            model_name='worldcupmodel',
            name='like_7',
            field=models.FloatField(default=1.7),
        ),
        migrations.AlterField(
            model_name='worldcupmodel',
            name='like_8',
            field=models.FloatField(default=1.8),
        ),
    ]
