# Generated by Django 3.2.4 on 2021-07-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
