# Generated by Django 3.2.4 on 2021-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_auto_20210708_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecreatemodel',
            name='article_text',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articlecreatemodel',
            name='article_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
