# Generated by Django 3.2.4 on 2021-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_auto_20210708_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecreatemodel',
            name='article_title',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
