# Generated by Django 3.2.4 on 2021-07-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
        ('articleapp', '0007_alter_articlecreatemodel_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecreatemodel',
            name='article_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='projectapp.projectcreatemodel'),
        ),
    ]
